apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-1-deployment
  namespace: dummiest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi1
  template:
    metadata:
      labels:
        app: fastapi1
    spec:
      containers:
      - name: fastapi1
        image: sanhan2/dummiest-fastapi1
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"   # 최소 메모리 요청
            cpu: "250m"       # 최소 CPU 요청
          limits:
            memory: "512Mi"   # 최대 메모리 제한
            cpu: "500m"       # 최대 CPU 제한
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-1-service
  namespace: dummiest
spec:
  selector:
    app: fastapi1
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP