apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: dummiest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: sanhan2/dummiest-streamlit-front
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "256Mi"   # 최소 메모리 요청
            cpu: "250m"       # 최소 CPU 요청
          limits:
            memory: "512Mi"   # 최대 메모리 제한
            cpu: "500m"       # 최대 CPU 제한
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: dummiest
spec:
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 80       # 외부 접속 포트 (예: http://192.168.49.103)
    targetPort: 8501
  type: LoadBalancer  # 외부에 노출
  loadBalancerIP: 192.168.49.103 # MetalLB 고정 IP
